### ISSUE TITLE
let's slim down the fabric8-online-team to include just Jenkins & content repo

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-online#16]
we may wanna add git-collector too when it's ported to go

Might be time to make a fabric8-online-system too?

Wonder if we can avoid needing exposecontroller too? E.g. Using it in the pipeline as a build step?

**Comment by jstrachan** [comment]
Also need to check that maven can deploy to content repo

**Comment by rawlingsj** [comment]
All done, we also have Che in there too https://github.com/fabric8io/fabric8-online#local-deploy
