### ISSUE TITLE
strategy type: recreate lost from output

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-online#165]
Che defines a DC strategy type Recreate, but that seems to be removed from output: 
https://github.com/fabric8io/fabric8-online/blob/master/apps/che/src/main/fabric8/deployment.yml#L4

http://central.maven.org/maven2/io/fabric8/online/packages/fabric8-online-che/1.0.103/fabric8-online-che-1.0.103-openshift.yml

**Comment by rawlingsj** [comment]
Sounds like f-m-p is removing it.  I wonder if it's because this is an openshift specific thing compared with kubernetes deployments.  We could maybe use a RAW type in the short term.  Will take a look.

**Comment by jstrachan** [comment]
it could be an FMP bug in the merging of the custom Deployment versus the generated one. I'll have a looksie

**Comment by rawlingsj** [comment]
ok great thanks!

**Comment by jstrachan** [comment]
raised https://github.com/fabric8io/fabric8-maven-plugin/issues/919 will hopefully have a fix soon

**Comment by jstrachan** [comment]
there's a fix here https://github.com/fabric8io/fabric8-maven-plugin/pull/920 just need to wait for it to be approved & released then upgrade to the new fmp version

**Comment by rawlingsj** [comment]
nice
